### PR TITLE
feat/RSS-ECOMM-3_09: Fetch and Display Product Details using Commercetools API

### LINKED ISSUE #29: Display Product Information
## Related issues in RS task

- [x] [Issue RSS-ECOMM-3_09: Fetch and Display Product Details using Commercetools API](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_09.md)
- [x] [Issue RSS-ECOMM-3_10: Implement an Image Slider for Product Images](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_10.md)
- [x] [Issue RSS-ECOMM-3_11: Display Product Price and Sale Price](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_11.md)

### PR DESCRIPTION
**Pull request by SvetaIlina**
## Overview
Please provide a brief summary of what this pull request accomplishes. Include the motivation behind these changes and the impact they aim to have on the project.

**What has been done:**
- add components and styles for displaying Products info
- add fetching products data function

**Why this has been done:**
- to display current information about the selected product on the page

**Issue(s) closed:**
- [RSS-ECOMM-3_09](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_09.md)

## Type of Change
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Screenshots
image

## Checklist:
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by makarovaiuliia** [comment]
Не могу выбрать размер почему то при клике

**Comment by SvetaIlina** [comment]
> Не могу выбрать размер почему то при клике

еще не реализовывала, это думаю, будет на этапе добавления в корзину

**Comment by Pavel-Kuvshinov** [comment]
Наверное выбор размера еще как и адаптив? А так все хорошо.

**Review by Pavel-Kuvshinov — COMMENTED** [review]
Наверное выбор размера еще как и адаптив? А так все хорошо.

**Comment by SvetaIlina** [comment]
> Наверное выбор размера еще как и адаптив? А так все хорошо.

адаптив хочу после добавления слайдера и модалки

**Review by makarovaiuliia — APPROVED** [review]
Тогда мерджим)

**Pull request merged**
